apiVersion: apps/v1
kind: Deployment
metadata: { name: sample-ha-app }
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: { type: RollingUpdate }
  selector: { matchLabels: { app: sample-ha-app } }
  template:
    metadata:
      labels:
        app: sample-ha-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector: { matchLabels: { app: sample-ha-app } }
      containers:
        - name: app
          image: {{ .Values.image }}
          ports: [{ containerPort: 80 }]
