falco:
  grpc:
    enabled: true
  grpcOutput:
    enabled: true
  
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d

  json_output: true
  json_include_output_property: true
  
  priority: warning
  
  syscall_event_drops:
    actions:
      - log
      - alert
    rate: 0.03333
    max_burst: 1000

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

falcosidekick:
  enabled: true
  webui:
    enabled: true
    service:
      type: NodePort