apiVersion: v1
kind: Namespace
metadata: { name: kube-system }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  selector: { matchLabels: { k8s-app: aws-cloud-controller-manager } }
  template:
    metadata: { labels: { k8s-app: aws-cloud-controller-manager } }
    spec:
      serviceAccountName: aws-cloud-controller-manager
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
      containers:
        - name: aws-cloud-controller-manager
          image: registry.k8s.io/provider-aws/cloud-controller-manager:v1.28.0
          command:
            - /bin/aws-cloud-controller-manager
            - --cloud-provider=aws
            - --configure-cloud-routes=false
            - --cluster-name=ha-cluster
            - --leader-elect=true
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: aws-cloud-controller-manager, namespace: kube-system }
