apiVersion: v1
kind: Namespace
metadata: { name: kyverno }
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata: { name: kyverno, namespace: kyverno }
spec:
  chart: kyverno/kyverno
  repo: https://kyverno.github.io/kyverno/
  targetNamespace: kyverno
  valuesContent: |
    replicaCount: 3
