name: ci-cd
on:
  push:
    branches: ["main"]
    paths: ["apps/sample-ha-app/**", "ci/github-actions-deploy.yaml"]

jobs:
  build-scan-sign-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/sample-ha-app
          push: true
          tags: ghcr.io/${{ github.repository }}/sample-ha-app:${{ github.sha }}

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/sample-ha-app:${{ github.sha }}
          format: table
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign image (keyless)
        run: cosign sign ghcr.io/${{ github.repository }}/sample-ha-app:${{ github.sha }} --yes
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Update values (image tag)
        run: |
          sed -i "s#^image: .*#image: ghcr.io/${{ github.repository }}/sample-ha-app:${{ github.sha }}#" apps/sample-ha-app/values.yaml

      - name: Deploy via kubectl (optional; requires secret)
        if: secrets.KUBECONFIG_B64 != ''
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
        run: |
          echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install sample-ha-app ./apps/sample-ha-app -n apps --create-namespace
